on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  post_pr_tag:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            const SANITIZED_BRANCH_NAME = '${{ github.event.pull_request.head.ref }}'.replaceAll("/", "-")
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/pull-request/PR#${{ github.event.number }}-${{ SANITIZED_BRANCH_NAME }}',
              sha: context.sha
            })