on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  post_pr_tag:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/PR#${{ github.event.number }}',
              sha: ${{ github.event.pull_request.head.sha }}
            })